volumes:
  timetable_local_postgres_data: {}
  timetable_local_postgres_data_backups: {}
  timetable_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: timetable_local_django
    container_name: timetable_local_django
    depends_on:
      - postgres
      - redis
      - opensearch
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: timetable_production_postgres
    container_name: timetable_local_postgres
    volumes:
      - timetable_local_postgres_data:/var/lib/postgresql/data
      - timetable_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: docker.io/redis:6
    container_name: timetable_local_redis

    volumes:
      - timetable_local_redis_data:/data

  celeryworker:
    <<: *django
    image: timetable_local_celeryworker
    container_name: timetable_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: timetable_local_celerybeat
    container_name: timetable_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: timetable_local_flower
    container_name: timetable_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  opensearch:
    image: opensearchproject/opensearch:2.8.0
    container_name: timetable_local_opensearch_backend
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
