# Generated by Django 5.1.7 on 2025-07-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_student_password_teacher_password_alter_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=50, verbose_name='Базовый пароль'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(blank=True, max_length=50, verbose_name='Базовый пароль'),
        ),
    ]
