# Generated by Django 5.0.13 on 2025-03-25 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='time_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timesubject'),
        ),
    ]
