# Generated by Django 5.1.7 on 2025-04-07 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='faculty',
        ),
        migrations.AddField(
            model_name='subject',
            name='subgroup',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type_of_classes',
            field=models.CharField(max_length=20, verbose_name='тип занятия'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type_of_day',
            field=models.CharField(max_length=20, verbose_name='день недели'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type_of_week',
            field=models.CharField(max_length=20, verbose_name='тип недели'),
        ),
        migrations.AlterField(
            model_name='timesubject',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='номер пары по счету'),
        ),
        migrations.CreateModel(
            name='ErrorSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('audience', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_day', models.CharField(blank=True, max_length=20, null=True, verbose_name='день недели')),
                ('type_of_week', models.CharField(blank=True, max_length=20, null=True, verbose_name='тип недели')),
                ('type_of_classes', models.CharField(blank=True, max_length=20, null=True, verbose_name='тип занятия')),
                ('teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('subgroup', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cause_of_error', models.TextField(blank=True, null=True)),
                ('time_subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.timesubject')),
            ],
            options={
                'verbose_name': 'предмет с ошибкой',
                'verbose_name_plural': 'предметы с ошибками',
            },
        ),
    ]
