# Generated by Django 5.1.7 on 2025-04-08 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_subject_faculty_subject_subgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorsubject',
            name='time_subject',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.timesubject'),
        ),
    ]
