# Generated by Django 5.1.7 on 2025-05-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_errorsubject_time_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type_of_classes',
            field=models.CharField(choices=[('lecture', 'Лекция'), ('practice', 'Практическое занятие'), ('laboratory', 'Лабораторное занятие')], default='', max_length=30, verbose_name='тип занятия'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type_of_day',
            field=models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота')], default='', max_length=20, verbose_name='день недели'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type_of_week',
            field=models.CharField(choices=[('numerator', 'Числитель'), ('denominator', 'Знаменатель')], default='', max_length=20, verbose_name='тип недели'),
        ),
    ]
