# Generated by Django 5.1.7 on 2025-06-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type_of_classes',
            field=models.CharField(choices=[('Лекция', 'Лекция'), ('Практическое занятие', 'Практическое занятие'), ('Лабораторное занятие', 'Лабораторное занятие')], default='', max_length=30, verbose_name='тип занятия'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type_of_day',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота')], default='', max_length=20, verbose_name='день недели'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type_of_week',
            field=models.CharField(choices=[('числитель', 'Числитель'), ('знаменатель', 'Знаменатель')], default='', max_length=20, verbose_name='тип недели'),
        ),
    ]
