# Generated by Django 5.1.7 on 2025-06-24 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_subject_type_of_classes_and_more'),
        ('users', '0003_alter_teacher_first_name_alter_teacher_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='audience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.audience', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subgroup',
            field=models.PositiveSmallIntegerField(verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='users.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='time_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timesubject', verbose_name='Время пары'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type_of_classes',
            field=models.CharField(choices=[('Лекция', 'Лекция'), ('Практическое занятие', 'Практическое занятие'), ('Лабораторное занятие', 'Лабораторное занятие')], default='', max_length=30, verbose_name='Тип занятия'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type_of_day',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота')], default='', max_length=20, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type_of_week',
            field=models.CharField(choices=[('Числитель', 'Числитель'), ('Знаменатель', 'Знаменатель')], default='', max_length=20, verbose_name='Тип недели'),
        ),
        migrations.AlterField(
            model_name='timesubject',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания пары'),
        ),
        migrations.AlterField(
            model_name='timesubject',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала пары'),
        ),
        migrations.DeleteModel(
            name='ErrorSubject',
        ),
    ]
