# Generated by Django 5.1.7 on 2025-06-25 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_audience_name_alter_faculty_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Дата начала учебного семестра')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='Дата окончания учебного семестра')),
                ('week_type', models.CharField(choices=[('Числитель', 'Числитель'), ('Знаменатель', 'Знаменатель')], max_length=20, verbose_name='Тип недели (Ч/З)')),
            ],
            options={
                'verbose_name': 'опорная дата расписания',
                'verbose_name_plural': 'опорная дата расписания',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата проведения занятия'),
        ),
    ]
