# Generated by Django 5.1.7 on 2025-07-28 09:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_scheduleanchor_subject_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='type_of_day',
        ),
        migrations.AddField(
            model_name='subject',
            name='rule_of_repeat',
            field=models.CharField(choices=[('Без повторения', 'Без повторения'), ('Каждую неделю', 'Каждую неделю'), ('Каждые 2 недели', 'Каждые 2 недели')], default='Без повторения', max_length=30, verbose_name='Правило повторения'),
        ),
        migrations.AlterField(
            model_name='scheduleanchor',
            name='week_type',
            field=models.CharField(choices=[('Числитель', 'Числитель'), ('Знаменатель', 'Знаменатель'), ('Автоматически', 'Автоматически')], max_length=20, verbose_name='Тип недели (Ч/З) в день начала занятий'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата проведения первого занятия'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type_of_week',
            field=models.CharField(choices=[('Числитель', 'Числитель'), ('Знаменатель', 'Знаменатель'), ('Автоматически', 'Автоматически')], default='', max_length=20, verbose_name='Тип недели'),
        ),
        migrations.CreateModel(
            name='SubjectRepeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeat_dates', to='core.subject')),
            ],
            options={
                'verbose_name': 'повторяющаяся дата предмета',
                'verbose_name_plural': 'повторяющиеся даты предметов',
                'indexes': [models.Index(fields=['date'], name='core_subjec_date_503925_idx')],
            },
        ),
    ]
