# Generated by Django 5.1.7 on 2025-07-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_subject_type_of_day_subject_rule_of_repeat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleanchor',
            name='week_type',
            field=models.CharField(choices=[('NUM', 'Числитель'), ('DEN', 'Знаменатель')], max_length=20, verbose_name='Тип недели (Ч/З) в день начала занятий'),
        ),
    ]
