# Generated by Django 5.1.7 on 2025-07-31 13:40

import timetable.core.utils.calculation_of_the_type_of_week
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_scheduleanchor_week_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleanchor',
            name='end_date',
            field=models.DateField(default=timetable.core.utils.calculation_of_the_type_of_week.default_end_date, verbose_name='Дата окончания учебного семестра'),
        ),
        migrations.AlterField(
            model_name='scheduleanchor',
            name='week_type',
            field=models.CharField(choices=[('Числитель', 'Числитель'), ('Знаменатель', 'Знаменатель')], default='Числитель', max_length=20, verbose_name='Тип недели (Ч/З) в день начала занятий'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type_of_week',
            field=models.CharField(choices=[('Числитель', 'Числитель'), ('Знаменатель', 'Знаменатель'), ('Автоматически', 'Автоматически')], default='Автоматически', max_length=20, verbose_name='Тип недели'),
        ),
    ]
