# Generated by Django 5.1.7 on 2025-08-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_scheduleanchor_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subgroup',
            field=models.PositiveSmallIntegerField(help_text='Укажите номер подгруппы: 1 или 2 для практик и лабораторных. Для лекций укажите 3 (означает: для всей группы).', verbose_name='Подгруппа'),
        ),
    ]
