name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

  push:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      # Consider using pre-commit.ci for open source project
      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

  # With no caching at all the entire ci process takes 3m to complete!
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Build the Stack
        run: docker compose -f docker-compose.test.yml build django

      - name: Check DB Migrations
        run: docker compose -f docker-compose.test.yml run --rm django python manage.py makemigrations --check

      - name: Run DB Migrations
        run: docker compose -f docker-compose.test.yml run --rm django python manage.py migrate

#      - name: mypy
#        run: docker compose -f docker-compose.local.yml run --rm django mypy .

      - name: Run Django Tests
        run: docker compose -f docker-compose.test.yml run django pytest

      - name: Tear down the Stack
        run: docker compose -f docker-compose.test.yml down --rmi all

      - name: Remove all stopped containers
        run: docker ps -aq | xargs -r docker rm

      - name: Delete docker image
        run: docker image rm -f timetable_test_django
